// GENERATED by scripts/build-rules.mjs — do not edit.
// Source of truth: src/rules.ts and everything it re-exports.
// src/config.ts
var TABLE_SCALE = 1.25;
var TABLE = {
  length: 3 * TABLE_SCALE,
  width: 1.5 * TABLE_SCALE,
  halfLen: 1.5 * TABLE_SCALE,
  halfWid: 0.75 * TABLE_SCALE,
  hCenter: 0.76 * TABLE_SCALE,
  hEnd: 0.565 * TABLE_SCALE,
  curveK: (0.76 - 0.565) / (1.5 * 1.5 * TABLE_SCALE),
  netTop: 0.9 * TABLE_SCALE,
  netHalfWidth: 0.85 * TABLE_SCALE
};
var PLAY_BOX = {
  halfLen: TABLE.halfLen + 0.3,
  halfWid: TABLE.halfWid + 0.32
};
var BALL_RADIUS = 0.08095 * TABLE_SCALE;
var COURT = {
  minX: TABLE.halfLen + 0.06,
  // players stay behind the table end
  maxX: 6.8,
  maxZ: 4.6
};
var SPAWN = {
  x: 2.64 * TABLE_SCALE,
  // distance from the net along the table axis
  z: 0,
  // lateral offset (+z = controlled player's left)
  lift: 0
  // extra y lift if a model's feet still sink into the floor
};
var CHARACTER_SCALE = 0.8 * TABLE_SCALE;
var SIM_HZ = 60;
var SIM_DT = 1 / SIM_HZ;
var SERVE_X = 3.64 * TABLE_SCALE;
var MAX_TOUCHES = 3;
var PLAYER_REACH = 1.2 * TABLE_SCALE;
var AI_REACH = 1.2 * TABLE_SCALE;
var WIN_SCORE = 3;
var SETS_TO_WIN = 2;
var CHARACTERS = [
  { id: "BrazilianPlayer", label: "BRAZIL", height: 1.76, strongFoot: "right", speed: 5.4, power: 1, precision: 1.1, backflips: "both" },
  { id: "EnglishPlayer", label: "ENGLAND", height: 1.86, strongFoot: "right", speed: 4.5, power: 1.7, precision: 0.9, backflips: "none" },
  { id: "FrenchPlayer", label: "FRANCE", height: 1.8, strongFoot: "left", speed: 5, power: 1.05, precision: 1, backflips: "strong" },
  { id: "SpanishPlayer", label: "SPAIN", height: 1.72, strongFoot: "both", speed: 4.9, power: 0.95, precision: 1.2, backflips: "strong" }
];

// src/challenges.ts
var POOL = [
  { id: "play3", kind: "matches", goal: 3, reward: 120 },
  { id: "play5", kind: "matches", goal: 5, reward: 200 },
  { id: "win1", kind: "wins", goal: 1, reward: 100 },
  { id: "win3", kind: "wins", goal: 3, reward: 250 },
  { id: "points10", kind: "points", goal: 10, reward: 130 },
  { id: "points20", kind: "points", goal: 20, reward: 220 },
  { id: "rally5", kind: "rallies", goal: 5, reward: 160 },
  { id: "rally10", kind: "rallies", goal: 10, reward: 260 },
  { id: "sets2", kind: "sets", goal: 2, reward: 140 },
  { id: "sets4", kind: "sets", goal: 4, reward: 240 }
];
var ALL_CHALLENGES = POOL;
var DAILY_COUNT = 3;
function dayKey(now) {
  const y = now.getFullYear();
  const m = `${now.getMonth() + 1}`.padStart(2, "0");
  const d = `${now.getDate()}`.padStart(2, "0");
  return `${y}-${m}-${d}`;
}
function hash(text) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function dailyChallenges(day) {
  const picked = [];
  const kinds = /* @__PURE__ */ new Set();
  const start = hash(day) % POOL.length;
  for (let i = 0; i < POOL.length && picked.length < DAILY_COUNT; i++) {
    const candidate = POOL[(start + i) % POOL.length];
    if (kinds.has(candidate.kind)) continue;
    kinds.add(candidate.kind);
    picked.push(candidate);
  }
  return picked;
}
function creditFor(kind, tally) {
  switch (kind) {
    case "matches":
      return 1;
    case "wins":
      return tally.won ? 1 : 0;
    case "points":
      return tally.points;
    case "sets":
      return tally.sets;
    case "rallies":
      return tally.rallies;
  }
}
function isComplete(challenge, progress) {
  return progress >= challenge.goal;
}
function secondsUntilRollover(now) {
  const midnight = new Date(now);
  midnight.setHours(24, 0, 0, 0);
  return Math.max(0, Math.round((midnight.getTime() - now.getTime()) / 1e3));
}

// src/league.ts
var TIERS = [
  { id: "beginner", label: "BEGINNER", floor: 0, bonus: 0 },
  { id: "rookie1", label: "ROOKIE I", floor: 60, bonus: 0.1 },
  { id: "rookie2", label: "ROOKIE II", floor: 160, bonus: 0.2 },
  { id: "rookie3", label: "ROOKIE III", floor: 300, bonus: 0.3 },
  { id: "junior1", label: "JUNIOR I", floor: 500, bonus: 0.4 },
  { id: "junior2", label: "JUNIOR II", floor: 760, bonus: 0.5 },
  { id: "pro1", label: "PRO I", floor: 1100, bonus: 0.65 },
  { id: "pro2", label: "PRO II", floor: 1550, bonus: 0.8 },
  { id: "elite", label: "ELITE", floor: 2100, bonus: 1 }
];
function tierFor(trophies) {
  let found = TIERS[0];
  for (const tier of TIERS) {
    if (trophies >= tier.floor) found = tier;
  }
  return found;
}
function nextTier(trophies) {
  return TIERS.find((tier) => tier.floor > trophies) ?? null;
}
function tierProgress(trophies) {
  const here = tierFor(trophies);
  const next = nextTier(trophies);
  if (!next) return 1;
  return Math.min(1, Math.max(0, (trophies - here.floor) / (next.floor - here.floor)));
}
var STAKE = {
  easy: { win: 12, loss: 10 },
  normal: { win: 20, loss: 12 },
  hard: { win: 30, loss: 14 }
};
function trophyDelta(won, difficulty, trophies) {
  const stake = STAKE[difficulty];
  if (won) return stake.win;
  if (trophies <= 0) return 0;
  return -Math.min(stake.loss, trophies);
}
var PURSE = {
  easy: { win: 40, loss: 12 },
  normal: { win: 70, loss: 20 },
  hard: { win: 110, loss: 30 }
};
function coinsFor(won, difficulty, trophies) {
  const purse = PURSE[difficulty];
  const base = won ? purse.win : purse.loss;
  return Math.round(base * (1 + tierFor(trophies).bonus));
}
function rankChange(before, after) {
  const from = tierFor(before);
  const to = tierFor(after);
  if (from.id === to.id) return null;
  return to.floor > from.floor ? "promoted" : "relegated";
}

// src/progress.ts
var STARTING_CHAMPION = CHARACTERS[0].id;
function freshCareer(day) {
  return {
    coins: 0,
    trophies: 0,
    best: 0,
    // Everyone starts with one player. The rest are the reason to keep playing.
    champions: { [STARTING_CHAMPION]: { level: 1, xp: 0 } },
    day,
    progress: {},
    claimed: []
  };
}
var UNLOCK_AT = {
  [CHARACTERS[0].id]: 0,
  [CHARACTERS[1].id]: 60,
  [CHARACTERS[2].id]: 160,
  [CHARACTERS[3].id]: 300
};
var XP_PER_LEVEL = 3;
function upgradeCost(level) {
  return 150 + (level - 1) * 120;
}
var MAX_LEVEL = 6;
function withCareer(def, level) {
  const steps = Math.max(0, Math.min(MAX_LEVEL, level) - 1);
  return { ...def, precision: def.precision * (1 + 0.09 * steps) };
}
function levelOf(career, id) {
  return career.champions[id]?.level ?? 1;
}
function isUnlocked(career, id) {
  if (career.champions[id]) return true;
  return career.best >= (UNLOCK_AT[id] ?? Infinity);
}
function rollOver(career, today) {
  if (career.day === today) return career;
  return { ...career, day: today, progress: {}, claimed: [] };
}
function settleMatch(career, championId, difficulty, tally, now = /* @__PURE__ */ new Date()) {
  const rolled = rollOver(career, dayKey(now));
  const trophies = trophyDelta(tally.won, difficulty, rolled.trophies);
  const coins = coinsFor(tally.won, difficulty, rolled.trophies);
  const after = Math.max(0, rolled.trophies + trophies);
  const champions = { ...rolled.champions };
  const current = champions[championId] ?? { level: 1, xp: 0 };
  const levelled = [];
  const xp = current.xp + 1;
  if (xp >= XP_PER_LEVEL && current.level < MAX_LEVEL) {
    champions[championId] = { level: current.level + 1, xp: 0 };
    levelled.push(championId);
  } else {
    champions[championId] = { ...current, xp };
  }
  const progress = { ...rolled.progress };
  const completed = [];
  for (const challenge of dailyChallenges(rolled.day)) {
    const before = progress[challenge.id] ?? 0;
    if (isComplete(challenge, before)) continue;
    const next = before + creditFor(challenge.kind, tally);
    progress[challenge.id] = next;
    if (isComplete(challenge, next)) completed.push(challenge.id);
  }
  return {
    career: {
      ...rolled,
      coins: rolled.coins + coins,
      trophies: after,
      best: Math.max(rolled.best, after),
      champions,
      progress
    },
    outcome: { trophies, coins, rank: rankChange(rolled.trophies, after), levelled, completed }
  };
}
function claimChallenge(career, id) {
  if (career.claimed.includes(id)) return career;
  const challenge = dailyChallenges(career.day).find((c) => c.id === id);
  if (!challenge) return career;
  if (!isComplete(challenge, career.progress[id] ?? 0)) return career;
  return { ...career, coins: career.coins + challenge.reward, claimed: [...career.claimed, id] };
}
function buyUpgrade(career, id) {
  const level = levelOf(career, id);
  if (level >= MAX_LEVEL) return career;
  if (!isUnlocked(career, id)) return career;
  const cost = upgradeCost(level);
  if (career.coins < cost) return career;
  return {
    ...career,
    coins: career.coins - cost,
    champions: { ...career.champions, [id]: { level: level + 1, xp: career.champions[id]?.xp ?? 0 } }
  };
}
export {
  ALL_CHALLENGES,
  CHARACTERS,
  DAILY_COUNT,
  MAX_LEVEL,
  MAX_TOUCHES,
  SETS_TO_WIN,
  STARTING_CHAMPION,
  TIERS,
  UNLOCK_AT,
  WIN_SCORE,
  XP_PER_LEVEL,
  buyUpgrade,
  claimChallenge,
  coinsFor,
  creditFor,
  dailyChallenges,
  dayKey,
  freshCareer,
  isComplete,
  isUnlocked,
  levelOf,
  nextTier,
  rankChange,
  rollOver,
  secondsUntilRollover,
  settleMatch,
  tierFor,
  tierProgress,
  trophyDelta,
  upgradeCost,
  withCareer
};
