// GENERATED by scripts/build-rules.mjs — do not edit.
// Source of truth: src/rules.ts and everything it re-exports.
// src/catalogue.ts
var CATALOGUE = {
  coins_handful: { kind: "coins", coins: 1200 },
  coins_pocket: { kind: "coins", coins: 3500 },
  coins_bag: { kind: "coins", coins: 9e3 },
  lifetime: { kind: "asset", asset: "gym" },
  venue_the_cage: { kind: "asset", asset: "basketball" },
  char_england: { kind: "asset", asset: "EnglishPlayer" },
  char_france: { kind: "asset", asset: "FrenchPlayer" },
  char_spain: { kind: "asset", asset: "SpanishPlayer" },
  bundle_champions: { kind: "asset", asset: "bundle_champions" },
  ball_surgeon: { kind: "asset", asset: "BlueBall" },
  ball_feather: { kind: "asset", asset: "BlueAndRoseBall" },
  ball_hammer: { kind: "asset", asset: "OrangeAndBlackBall" },
  bundle_balls: { kind: "asset", asset: "bundle_balls" }
};
var BUNDLES = {
  bundle_champions: ["EnglishPlayer", "FrenchPlayer", "SpanishPlayer"],
  bundle_balls: ["BlueBall", "BlueAndRoseBall", "OrangeAndBlackBall"]
};
function assetsFor(productId) {
  const grant = CATALOGUE[productId];
  if (!grant || grant.kind !== "asset") return [];
  return BUNDLES[grant.asset] ?? [grant.asset];
}
function coinsForPurchase(productId) {
  const grant = CATALOGUE[productId];
  return grant?.kind === "coins" ? grant.coins : 0;
}

// src/config.ts
var TABLE_SCALE = 1.25;
var TABLE = {
  length: 3 * TABLE_SCALE,
  width: 1.5 * TABLE_SCALE,
  halfLen: 1.5 * TABLE_SCALE,
  halfWid: 0.75 * TABLE_SCALE,
  hCenter: 0.76 * TABLE_SCALE,
  hEnd: 0.565 * TABLE_SCALE,
  curveK: (0.76 - 0.565) / (1.5 * 1.5 * TABLE_SCALE),
  netTop: 0.9 * TABLE_SCALE,
  netHalfWidth: 0.85 * TABLE_SCALE
};
var PLAY_BOX = {
  halfLen: TABLE.halfLen + 0.3,
  halfWid: TABLE.halfWid + 0.32
};
var BALL_RADIUS = 0.08095 * TABLE_SCALE;
var COURT = {
  // Players may come right up to the middle line. They used to be held behind
  // the table *end*, nearly two metres off the net, which made the whole front
  // of the court unreachable and the hardest shots — the ones taken close in —
  // impossible to play. What they cannot do is stand on the table; that is
  // `clearTable` below, and it is a hole in the middle of the half rather than
  // a wall across it.
  minX: 0.06,
  maxX: 6.8,
  maxZ: 4.6
};
var SPAWN = {
  x: 2.64 * TABLE_SCALE,
  // distance from the net along the table axis
  z: 0,
  // lateral offset (+z = controlled player's left)
  lift: 0
  // extra y lift if a model's feet still sink into the floor
};
var CHARACTER_SCALE = 0.8 * TABLE_SCALE;
var ANCHOR_STEP_BACK = 0.24 * TABLE_SCALE;
var RECEPTION_ZONE = {
  /**
   * Free radius around the anchor: full control, no damping at all (m).
   *
   * Derived, not chosen. The anchor stands `ANCHOR_STEP_BACK` behind the drop
   * so the ball comes down in front of the player, which puts the ball that
   * much *further* away than the anchor is — so a free radius set any wider
   * than `AUTO_RECEPTION_REACH - ANCHOR_STEP_BACK` opens a band where the
   * player is told their feet are their own and then cannot reach the ball
   * from where they stood. That band is what stranded an idle player just
   * outside a reception that was theirs to make.
   *
   * `1.36 - 0.24 = 1.12`, in the same table units as everything else here.
   */
  radius: 1.12 * TABLE_SCALE,
  /** Beyond the radius, the band the outward push fades across (m). */
  soft: 0.85 * TABLE_SCALE,
  /** What is left of an outward push at the far edge of the soft band. */
  minPush: 0.18,
  /**
   * Speed the leash draws a player back from beyond the band (m/s).
   *
   * This is the assisted shift itself, so it has to be worth something: at a
   * walking pace it closed a quarter of a two-metre gap in the time a ball
   * takes to come down, which is help the player can feel and cannot use.
   *
   * What keeps it an assist rather than a lock is not its size but its shape.
   * It fades out with how hard the player is pushing and is gone entirely at
   * full stick, so a held push always wins and leaving is always a decision
   * they can make; and it can never exceed a full run, so nothing here moves
   * anybody faster than their own legs would.
   */
  leash: 2.56 * TABLE_SCALE,
  /**
   * Hard cap around a set-up the player made themselves (m).
   *
   * The soft zone above is the right answer for a ball coming *at* you: you
   * may still decide to leave it. A ball you put up yourself is different —
   * it is already in the air and going nowhere else, so leaving is not a
   * decision left to make halfway through, and the soft zone let a player
   * walk off their own set-up while it dropped.
   *
   * Deliberately small: this is room to circle the drop and choose which foot
   * takes it, not room to reposition. Scaled like every other distance here,
   * and well inside `PLAYER_REACH`, so a ball landing on the anchor stays
   * reachable from anywhere in the circle.
   */
  hardCap: 0.64 * TABLE_SCALE
};
var SIDE_FOV = 1;
var SIDE_HALF_WIDTH = COURT.maxX + 0.6;
var SIDE_SLANT = SIDE_HALF_WIDTH / Math.tan(SIDE_FOV / 2);
var SIDE_PITCH = 0.87;
var PORTRAIT_FOV = 0.88;
var PORTRAIT_MARGIN = 0.5;
var PORTRAIT_SPREAD = Math.tan(PORTRAIT_FOV / 2);
var PORTRAIT_HALF_WIDTH = (COURT.maxZ + TABLE.halfWid) / 2 + PORTRAIT_MARGIN;
var PORTRAIT_STANDOFF = 2.2;
var PORTRAIT_SLANT = PORTRAIT_HALF_WIDTH / PORTRAIT_SPREAD;
var PORTRAIT_HEIGHT = Math.sqrt(
  Math.max(0, PORTRAIT_SLANT * PORTRAIT_SLANT - PORTRAIT_STANDOFF * PORTRAIT_STANDOFF)
);
var CAMERA = {
  back: 7.8,
  // distance behind the serve spot along the table axis (m)
  height: 6.2,
  // height above the ground (m)
  // Point along court axis the camera aims down at (towards table bed and court).
  lookX: -0.6,
  // Height above the ground the camera looks at. Lower = tilts cleanly down toward court floor.
  lookY: 0.15,
  /** Landscape lens, pinned vertically. Shared by the scene's default camera. */
  fov: 0.72,
  // Portrait is a tall, narrow window on the same court. The lens is pinned
  // horizontally there (see scene.ts), which makes the vertical angle very
  // wide — from the landscape distance the players end up specks in a frame
  // mostly full of roof. So portrait comes in closer and tilts up a little.
  // Portrait's lens cannot be tightened as far as landscape's looks like it
  // should allow. Pinned horizontally, the fov *is* the width of what can be
  // seen, and the narrowest part of the shot is right where the player stands:
  // squeeze it and a player chasing a wide ball walks out of their own frame.
  portrait: {
    // Solved above, expressed the way this table expresses everything else —
    // as a distance behind the serve spot — so the one call site does not have
    // to know which baseline the solve was measured from.
    back: COURT.maxX + PORTRAIT_STANDOFF - SPAWN.x,
    height: PORTRAIT_HEIGHT,
    lookX: -0.6,
    lookY: 0.15,
    fov: PORTRAIT_FOV,
    /** How far the camera may pan before the table leaves the frame. */
    pan: PORTRAIT_HALF_WIDTH - TABLE.halfWid,
    /**
     * How much of the visible half-width the player may use before the camera
     * starts to follow them.
     *
     * A deadzone, not a lock: inside this band the shot is still, and the
     * camera slides only as far as it must to bring them back inside it. A
     * camera welded to the player makes the world slide under a figure that
     * never moves, which is both harder to read and worse to look at.
     *
     * It has to exist at all because the shot narrows towards the near end.
     * The lens is pinned horizontally, so the visible width is proportional to
     * the distance from the camera — and a player at the back of their half is
     * only about a metre from either edge of frame. Now that the half runs all
     * the way to the middle line, they cover far more of it than they used to.
     */
    safe: 0.55,
    /** Seconds for the follow to catch up. Long enough to read as camera work. */
    tau: 0.22,
    /** Headroom in the solved framing, beside the table. */
    margin: PORTRAIT_MARGIN
  },
  /**
   * The shot held on whoever just won the game.
   *
   * A match ends with one player celebrating and the other playing Defeat, and
   * the locked-off court camera is too far away for either to read as anything
   * but a small figure. Coming in on the winner is what the moment is for.
   *
   * The camera sits in front of them — between them and the net, since that is
   * the side they are facing — and slightly off-axis, because a dead-centre
   * front-on shot of a rig is the one angle that looks like a character
   * selection screen rather than a celebration.
   */
  victory: {
    /** Metres in front of the winner, along the way they face. */
    distance: 3.4,
    /** Metres to their side, so the shot is not dead-on. */
    offset: 1.5,
    height: 1.9,
    /** Height on the winner the camera looks at: chest, not feet. */
    lookY: 1.25,
    fov: 0.95,
    /**
     * Seconds for the move in. Slow enough to read as a deliberate push rather
     * than a cut, short enough to arrive while the celebration is still going.
     */
    tau: 0.55
  },
  // P2 cannot use the mirrored P1 position: it lands outside the imported
  // gym. This keeps the view inside, matches P1's player scale, and gives it
  // a slightly steeper tilt.
  p2Court: {
    x: 8.5,
    height: 7,
    lookY: 0.3,
    fov: 1.1
  },
  // Side-on and overhead presets. Side cameras use the clear, opposite
  // sideline of the imported arena; the old wider placement intersected a
  // concourse prop in the frame.
  // Solved from the court, like the portrait shot, and for the same reason:
  // the old numbers put the lens 9.1 m from the middle of an 18 m court, so a
  // half-frame held 5.0 m of a half-court that is 6.8 m long and both ends
  // were simply outside the picture.
  //
  // Side-on, the court's *length* runs across the screen, which on a phone
  // held upright is its narrow dimension — so this view needs more distance
  // than the one behind the baseline, not less.
  side: {
    distance: SIDE_SLANT * Math.cos(SIDE_PITCH),
    height: SIDE_SLANT * Math.sin(SIDE_PITCH),
    lookY: 0.3,
    fov: SIDE_FOV,
    minZ: 0.1,
    /**
     * Near plane inside a closed venue, in metres.
     *
     * Far enough to clip the hall's near wall and the stands in front of it,
     * so a camera solved from the court can stand where the court needs it and
     * still see in. Comfortably short of the table.
     */
    indoorMinZ: 7.5
  }
};
var SIM_HZ = 60;
var SIM_DT = 1 / SIM_HZ;
var SERVE_X = 3.64 * TABLE_SCALE;
var MAX_TOUCHES = 3;
var PLAYER_REACH = 1.15 * TABLE_SCALE;
var AI_REACH = 1.15 * TABLE_SCALE;
var LUNGE_MAX = 0.55 * TABLE_SCALE;
var AUTO_RECEPTION_REACH = 1.36 * TABLE_SCALE;
var WIN_SCORE = 3;
var SETS_TO_WIN = 2;
var CHARACTERS = [
  // The beginner. Every trait sits at the bottom of its span, so every later
  // character and every level bought is felt against this one.
  {
    id: "BrazilianPlayer",
    label: "BRAZIL",
    height: 1.76,
    strongFoot: "right",
    speed: 4.5,
    power: 0.9,
    precision: 0.88,
    backflips: "strong",
    stamina: 0.82,
    serve: 0.85,
    agility: 0.95,
    volley: 0.88,
    weakFoot: 55,
    officialKitColor: "green",
    menuPose: "MenuPose_Backflip"
  },
  // The powerhouse. The hardest ball and the best serve in the game, and the
  // slowest to get going — a hammer of a right foot and very little on the
  // left, so the header is his answer to anything on that side.
  {
    id: "EnglishPlayer",
    label: "ENGLAND",
    height: 1.86,
    strongFoot: "right",
    speed: 4.7,
    power: 1.38,
    precision: 0.95,
    backflips: "none",
    stamina: 1.18,
    serve: 1.28,
    agility: 0.8,
    volley: 0.95,
    weakFoot: 50,
    officialKitColor: "white",
    officialKitFabricColor: "royal",
    officialKitShortsColor: "white",
    officialKitShortsFabricColor: "navy",
    shortsCrestColor: "white",
    officialKitNumber: "10",
    officialKitCrest: "shield",
    menuPose: "MenuPose"
  },
  // The all-rounder. Nothing to hide behind and nothing that lets him down,
  // and comfortably better than either player below him.
  {
    id: "FrenchPlayer",
    label: "FRANCE",
    height: 1.8,
    strongFoot: "left",
    speed: 5.3,
    power: 1.12,
    precision: 1.12,
    backflips: "strong",
    stamina: 1.1,
    serve: 1.1,
    agility: 1.15,
    volley: 1.12,
    weakFoot: 75,
    officialKitColor: "white",
    officialKitShortsColor: "navy",
    shortsCrestColor: "royal",
    menuPose: "MenuPose1"
  },
  // The technician, and the top of the ladder. Two-footed, so there is no weak
  // side to exploit and nothing forces a header.
  {
    id: "SpanishPlayer",
    label: "SPAIN",
    height: 1.72,
    strongFoot: "both",
    speed: 5.6,
    power: 1.05,
    precision: 1.34,
    backflips: "both",
    stamina: 1.16,
    serve: 1.05,
    agility: 1.3,
    volley: 1.4,
    weakFoot: 100,
    officialKitColor: "gold",
    menuPose: "MenuPose2"
  }
];

// src/challenges.ts
var POOL = [
  { id: "play3", kind: "matches", goal: 3, reward: 120 },
  { id: "play5", kind: "matches", goal: 5, reward: 200 },
  { id: "win1", kind: "wins", goal: 1, reward: 100 },
  { id: "win3", kind: "wins", goal: 3, reward: 250 },
  { id: "points10", kind: "points", goal: 10, reward: 130 },
  { id: "points20", kind: "points", goal: 20, reward: 220 },
  { id: "rally5", kind: "rallies", goal: 5, reward: 160 },
  { id: "rally10", kind: "rallies", goal: 10, reward: 260 },
  { id: "sets2", kind: "sets", goal: 2, reward: 140 },
  { id: "sets4", kind: "sets", goal: 4, reward: 240 }
];
var ALL_CHALLENGES = POOL;
var DAILY_COUNT = 3;
function dayKey(now) {
  const y = now.getFullYear();
  const m = `${now.getMonth() + 1}`.padStart(2, "0");
  const d = `${now.getDate()}`.padStart(2, "0");
  return `${y}-${m}-${d}`;
}
function hash(text) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function dailyChallenges(day) {
  const picked = [];
  const kinds = /* @__PURE__ */ new Set();
  const start = hash(day) % POOL.length;
  for (let i = 0; i < POOL.length && picked.length < DAILY_COUNT; i++) {
    const candidate = POOL[(start + i) % POOL.length];
    if (kinds.has(candidate.kind)) continue;
    kinds.add(candidate.kind);
    picked.push(candidate);
  }
  return picked;
}
function creditFor(kind, tally) {
  switch (kind) {
    case "matches":
      return 1;
    case "wins":
      return tally.won ? 1 : 0;
    case "points":
      return tally.points;
    case "sets":
      return tally.sets;
    case "rallies":
      return tally.rallies;
  }
}
function isComplete(challenge, progress) {
  return progress >= challenge.goal;
}
function secondsUntilRollover(now) {
  const midnight = new Date(now);
  midnight.setHours(24, 0, 0, 0);
  return Math.max(0, Math.round((midnight.getTime() - now.getTime()) / 1e3));
}

// src/league.ts
var TIERS = [
  { id: "beginner", label: "BEGINNER", floor: 0, bonus: 0 },
  { id: "rookie1", label: "ROOKIE I", floor: 60, bonus: 0.1 },
  { id: "rookie2", label: "ROOKIE II", floor: 160, bonus: 0.2 },
  { id: "rookie3", label: "ROOKIE III", floor: 300, bonus: 0.3 },
  { id: "junior1", label: "JUNIOR I", floor: 500, bonus: 0.4 },
  { id: "junior2", label: "JUNIOR II", floor: 760, bonus: 0.5 },
  { id: "pro1", label: "PRO I", floor: 1100, bonus: 0.65 },
  { id: "pro2", label: "PRO II", floor: 1550, bonus: 0.8 },
  { id: "elite", label: "ELITE", floor: 2100, bonus: 1 }
];
function tierFor(trophies) {
  let found = TIERS[0];
  for (const tier of TIERS) {
    if (trophies >= tier.floor) found = tier;
  }
  return found;
}
function nextTier(trophies) {
  return TIERS.find((tier) => tier.floor > trophies) ?? null;
}
function tierProgress(trophies) {
  const here = tierFor(trophies);
  const next = nextTier(trophies);
  if (!next) return 1;
  return Math.min(1, Math.max(0, (trophies - here.floor) / (next.floor - here.floor)));
}
var STAKE = {
  easy: { win: 8, loss: 6 },
  normal: { win: 14, loss: 10 },
  hard: { win: 20, loss: 14 },
  online: { win: 24, loss: 16 }
};
function trophyDelta(won, difficulty, trophies) {
  const stake = STAKE[difficulty];
  if (won) return stake.win;
  if (trophies <= 0) return 0;
  return -Math.min(stake.loss, trophies);
}
var PURSE = {
  easy: { win: 20, loss: 8 },
  normal: { win: 35, loss: 10 },
  hard: { win: 60, loss: 16 },
  online: { win: 75, loss: 20 }
};
function coinsFor(won, difficulty, trophies) {
  const purse = PURSE[difficulty];
  const base = won ? purse.win : purse.loss;
  return Math.round(base * (1 + tierFor(trophies).bonus));
}
function rankChange(before, after) {
  const from = tierFor(before);
  const to = tierFor(after);
  if (from.id === to.id) return null;
  return to.floor > from.floor ? "promoted" : "relegated";
}

// src/season.ts
function seasonKey(now) {
  return `${now.getFullYear()}-${`${now.getMonth() + 1}`.padStart(2, "0")}`;
}
function softReset(trophies) {
  return Math.max(0, Math.round(trophies / 2));
}
function seasonReward(tierId) {
  const index = TIERS.findIndex((t) => t.id === tierId);
  if (index <= 0) return 0;
  return index * 250;
}
function seasonTier(seasonBest) {
  return tierFor(seasonBest).label;
}
function seasonTierId(seasonBest) {
  return tierFor(seasonBest).id;
}

// src/ratings.ts
var SPAN = {
  reactivity: { min: 3.8, max: 6.6 },
  power: { min: 0.7, max: 1.8 },
  control: { min: 0.7, max: 1.9 },
  stamina: { min: 0.65, max: 1.8 },
  serve: { min: 0.7, max: 1.6 },
  agility: { min: 0.65, max: 1.8 },
  volley: { min: 0.7, max: 1.85 }
};

// src/progress.ts
var STARTING_CHAMPION = CHARACTERS[0].id;
var MAX_TITLES = 36;
function freshCareer(day, season = day.slice(0, 7)) {
  return {
    coins: 0,
    trophies: 0,
    best: 0,
    // Everyone starts with one player. The rest are the reason to keep playing.
    champions: { [STARTING_CHAMPION]: { level: 1, xp: 0 } },
    unlockedAssets: [],
    day,
    progress: {},
    claimed: [],
    season,
    seasonBest: 0,
    titles: [],
    drinks: {},
    taken: [],
    armed: null
  };
}
var UNLOCK_AT = {
  [CHARACTERS[0].id]: 0,
  [CHARACTERS[1].id]: 120,
  [CHARACTERS[2].id]: 300,
  [CHARACTERS[3].id]: 550
};
var XP_PER_LEVEL = 10;
function upgradeCost(level) {
  return 150 + (level - 1) * (150 + (level - 1) * 25);
}
var MAX_LEVEL = 25;
function withCareer(def, level) {
  const steps = Math.max(0, Math.min(MAX_LEVEL, level) - 1);
  const grow = (value, rate, key) => Math.min(SPAN[key].max, value * (1 + rate * steps));
  return {
    ...def,
    precision: grow(def.precision, 0.05, "control"),
    volley: grow(def.volley, 0.048, "volley"),
    stamina: grow(def.stamina, 0.051, "stamina"),
    power: grow(def.power, 0.043, "power"),
    serve: grow(def.serve, 0.038, "serve"),
    // The widest gap in the roster: ENGLAND starts at 0.80 where the starter
    // is at 0.95, so the rate that gets the *starter* there leaves ENGLAND
    // short of its own ceiling for good.
    agility: grow(def.agility, 0.053, "agility"),
    speed: grow(def.speed, 0.02, "reactivity")
  };
}
function levelOf(career, id) {
  return career.champions[id]?.level ?? 1;
}
function isUnlocked(career, id) {
  if (career.unlockedAssets?.includes(id)) return true;
  if (career.champions[id]) return true;
  return career.best >= (UNLOCK_AT[id] ?? Infinity);
}
function grantAssetUnlock(career, id) {
  const list = career.unlockedAssets ?? [];
  if (list.includes(id)) return career;
  const champions = { ...career.champions };
  if (CHARACTERS.some((c) => c.id === id) && !champions[id]) {
    champions[id] = { level: 1, xp: 0 };
  }
  return { ...career, unlockedAssets: [...list, id], champions };
}
function rollOver(career, today) {
  if (career.day === today) return career;
  return { ...career, day: today, progress: {}, claimed: [] };
}
function applySeason(career, now = /* @__PURE__ */ new Date()) {
  const key = seasonKey(now);
  if (career.season === key) return { career, ended: null };
  const from = career.trophies;
  const to = softReset(from);
  const rolled = { ...career, season: key, trophies: to, seasonBest: to };
  if (career.seasonBest <= 0) return { career: rolled, ended: null };
  const title = {
    season: career.season,
    tier: seasonTier(career.seasonBest),
    best: career.seasonBest
  };
  const coins = seasonReward(seasonTierId(career.seasonBest));
  return {
    career: {
      ...rolled,
      coins: rolled.coins + coins,
      titles: [...rolled.titles, title].slice(-MAX_TITLES)
    },
    ended: { title, coins, from, to }
  };
}
function settleMatch(career, championId, difficulty, tally, now = /* @__PURE__ */ new Date()) {
  const { career: rolled, ended } = applySeason(rollOver(career, dayKey(now)), now);
  const trophies = trophyDelta(tally.won, difficulty, rolled.trophies);
  const coins = coinsFor(tally.won, difficulty, rolled.trophies);
  const after = Math.max(0, rolled.trophies + trophies);
  const champions = { ...rolled.champions };
  const current = champions[championId] ?? { level: 1, xp: 0 };
  const levelled = [];
  const xp = current.xp + 1;
  if (xp >= XP_PER_LEVEL && current.level < MAX_LEVEL) {
    champions[championId] = { level: current.level + 1, xp: 0 };
    levelled.push(championId);
  } else {
    champions[championId] = { ...current, xp };
  }
  const progress = { ...rolled.progress };
  const completed = [];
  for (const challenge of dailyChallenges(rolled.day)) {
    const before = progress[challenge.id] ?? 0;
    if (isComplete(challenge, before)) continue;
    const next = before + creditFor(challenge.kind, tally);
    progress[challenge.id] = next;
    if (isComplete(challenge, next)) completed.push(challenge.id);
  }
  return {
    career: {
      ...rolled,
      coins: rolled.coins + coins,
      trophies: after,
      best: Math.max(rolled.best, after),
      seasonBest: Math.max(rolled.seasonBest, after),
      champions,
      progress
    },
    outcome: {
      trophies,
      coins,
      rank: rankChange(rolled.trophies, after),
      levelled,
      completed,
      season: ended
    }
  };
}
function claimChallenge(career, id) {
  if (career.claimed.includes(id)) return career;
  const challenge = dailyChallenges(career.day).find((c) => c.id === id);
  if (!challenge) return career;
  if (!isComplete(challenge, career.progress[id] ?? 0)) return career;
  return { ...career, coins: career.coins + challenge.reward, claimed: [...career.claimed, id] };
}
function buyUpgrade(career, id) {
  const level = levelOf(career, id);
  if (level >= MAX_LEVEL) return career;
  if (!isUnlocked(career, id)) return career;
  const cost = upgradeCost(level);
  if (career.coins < cost) return career;
  return {
    ...career,
    coins: career.coins - cost,
    champions: { ...career.champions, [id]: { level: level + 1, xp: career.champions[id]?.xp ?? 0 } }
  };
}
export {
  ALL_CHALLENGES,
  BUNDLES,
  CATALOGUE,
  CHARACTERS,
  DAILY_COUNT,
  MAX_LEVEL,
  MAX_TITLES,
  MAX_TOUCHES,
  SETS_TO_WIN,
  STARTING_CHAMPION,
  TIERS,
  UNLOCK_AT,
  WIN_SCORE,
  XP_PER_LEVEL,
  applySeason,
  assetsFor,
  buyUpgrade,
  claimChallenge,
  coinsFor,
  coinsForPurchase,
  creditFor,
  dailyChallenges,
  dayKey,
  freshCareer,
  grantAssetUnlock,
  isComplete,
  isUnlocked,
  levelOf,
  nextTier,
  rankChange,
  rollOver,
  seasonKey,
  seasonReward,
  seasonTier,
  seasonTierId,
  secondsUntilRollover,
  settleMatch,
  softReset,
  tierFor,
  tierProgress,
  trophyDelta,
  upgradeCost,
  withCareer
};
