// Bundles the career rules the server has to agree with into a plain ES module
// it can run.
//
// The server settles matches itself — a leaderboard built from totals the
// client posts is a list of whoever edited localStorage best — so it needs
// exactly the same arithmetic the client uses. Two copies of that arithmetic
// would disagree the first time either was tuned, so there is one copy, in
// `src/`, and this bundles it.
//
// The output is committed. `server/Dockerfile` deliberately copies only the
// server directory so the deployed image carries `ws` and nothing else, and
// giving it the whole build toolchain to regenerate one file would be a poor
// trade. `tests/rules.test.ts` fails if the committed bundle has drifted from
// the source, which is the part that actually matters.
//
//   node scripts/build-rules.mjs           # write server/rules.mjs
//   node scripts/build-rules.mjs --check   # exit 1 if it would change
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const OUT = fileURLToPath(new URL("../server/rules.mjs", import.meta.url));
const ENTRY = fileURLToPath(new URL("../src/rules.ts", import.meta.url));

const HEADER = `// GENERATED by scripts/build-rules.mjs — do not edit.
// Source of truth: src/rules.ts and everything it re-exports.
`;

export async function bundleRules() {
  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    // Readable rather than minified: this is committed, so a diff on it should
    // be reviewable and a stack trace from it should mean something.
    minify: false,
    write: false,
  });
  return HEADER + result.outputFiles[0].text;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const bundled = await bundleRules();
  if (process.argv.includes("--check")) {
    const current = readFileSync(OUT, "utf8");
    if (current !== bundled) {
      console.error("server/rules.mjs is stale — run: node scripts/build-rules.mjs");
      process.exit(1);
    }
    console.log("server/rules.mjs is up to date");
  } else {
    writeFileSync(OUT, bundled);
    console.log(`wrote ${OUT}`);
  }
}
